# Generated by Django 4.0.3 on 2022-03-15 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailconfirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
