# Generated by Django 4.0.3 on 2022-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailconfirmationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationcode',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
