# Generated by Django 4.0.3 on 2022-04-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_logincode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderation_status',
            field=models.CharField(default='on_moderation', max_length=32),
        ),
    ]
