# Generated by Django 4.0.3 on 2022-04-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('participants_limit', models.PositiveSmallIntegerField(blank=True, verbose_name='maximum number of participants')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='price in rubles')),
                ('link_to_chat', models.URLField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('publication_date', models.DateField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
