# Generated by Django 4.0.3 on 2022-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_link_to_chat_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum number of participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
