# Generated by Django 4.0.3 on 2022-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_participants_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_already_declined',
            field=models.BooleanField(default=False),
        ),
    ]
