# Generated by Django 4.0.3 on 2022-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_already_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_already_declined',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='event',
            name='moderation_status',
            field=models.CharField(default='on_moderation', max_length=32),
        ),
    ]
